version: '3.8'
services:
  mongo:
    image: mongo:7
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./mongo-data:/data/db

  backend:
    build:
      context: ./sport/backend
    container_name: sport-backend
    restart: always
    ports:
      - 8020:8020
    env_file:
      - ./sport/backend/.env
    depends_on:
      - mongo

  frontend:
    build:
      context: ./sport
    container_name: sport-frontend
    restart: always
    ports:
      - 8010:80
    depends_on:
      - backend
